### ISSUE TITLE
[ feature requeset ] Support SQLite

### ISSUE THREAD

**Issue by yonas** [raffomania/linkblocks#83]
It would be great to have support for a very lightweight DB with no setup requirements.

**Comment by raffomania** [comment]
Hey, I appreciate the sentiment. I'm a big fan of SQLite myself. However, since I'm only a one-man operation, supporting another DB besides PostgreSQL would be too much effort at the moment. Sorry!

**Comment by yonas** [comment]
Ok, I'll just leave this link here: https://diesel.rs/

**Comment by raffomania** [comment]
I've thought about this some more and want to reply a little bit more in-depth because I'd really, really like to support SQLite.

First, why don't I use something like diesel to abstract away the differences between PostgreSQL and SQLite? Experience has taught me that these abstractions are not foolproof, so supporting two databases still requires testing both of them to make sure everything works as intended. This would add friction to the development, making it slower to add new features. That's something I'd consider after linkblocks has reached version 1.0, when it's clear what functionality is useful and makes up the core of the app.

Second, I thought about replacing PostgreSQL with SQLite. I aim for linkblocks to work for deployments with about 100 concurrent users at any given time, and I'm quite confident that SQLite could handle that kind of load. I want to make it as easy as possible to self-host linkblocks, which is an area where SQLite shines. Even advanced features like JSON querying and indexing seem to be supported at least somewhat by SQLite.

My problem with SQLite is simply that I have little experience with it. I'm already exploring a new way to build the frontend of linkblocks, and learning the ins and outs of a new database would further slow down feature development.
Besides speed, this is also a matter of focus: With linkblocks, I want to learn about new ways to exchange and discuss knowledge. Additionally learning some new technology along the way is fine, but too much new stuff will cast a shadow over the main goal!

I understand that PostgreSQL adds to the operational burden when running linkblocks, but I hope I shed some light on why it's still the right database for the project when taking everything into account :)
